;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]
background = ${xrdb:background:#fbf1c7}
foreground = ${xrdb:foreground:#3c3836}
sep        = ${xrdb:color8:#504945}

color0  = ${xrdb:color0:#3c3836}
color1  = ${xrdb:color1:#c14a4a}
color2  = ${xrdb:color2:#6c782e}
color3  = ${xrdb:color3:#c35e0a}
color4  = ${xrdb:color4:#45707a}
color5  = ${xrdb:color5:#945e80}
color6  = ${xrdb:color6:#4c7a5d}
color7  = ${xrdb:color7:#bdae93}
color8  = ${xrdb:color8:#504945}
color9  = ${xrdb:color9:#cc241d}
color10 = ${xrdb:color10:#98971a}
color11 = ${xrdb:color11:#d79921}
color12 = ${xrdb:color12:#458588}
color13 = ${xrdb:color13:#b16286}
color14 = ${xrdb:color14:#689d6a}
color15 = ${xrdb:color15:#f2e5bc}

white     = ${xrdb:color15:#f2e5bc}
black     = ${xrdb:color0:#3c3836}
red       = ${xrdb:color1:#c14a4a}
pink      = ${xrdb:color5:#945e80}
purple    = ${xrdb:color5:#945e80}
blue      = ${xrdb:color4:#45707a}
cyan      = ${xrdb:color6:#4c7a5d}
teal      = ${xrdb:color6:#4c7a5d}
green     = ${xrdb:color2:#6c782e}
lime      = ${xrdb:color2:#6c782e}
yellow    = ${xrdb:color3:#c35e0a}
amber     = ${xrdb:color3:#c35e0a}
orange    = ${xrdb:color3:#c35e0a}
brown     = ${xrdb:color8:#504945}
indigo    = ${xrdb:color4:#45707a}
gray      = ${xrdb:color7:#bdae93}
blue-gray = ${xrdb:color8:#504945}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
