[FileDialog]
history=file:///home/Almighty42/Development/Code/Work/MSPM0G3507-System-Library/Testing/src, file:///home/Almighty42/Development/Code/Work/MSPM0G3507-System-Library/Testing/inc, file:///home/Almighty42/Downloads, file:///home/Almighty42/temp/162CANON, file:///home/Almighty42/Development/College/PITS
lastVisited=file:///home/Almighty42/Downloads
qtVersion=6.11.1
shortcuts=file:, file:///home/Almighty42
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x33\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\xc8\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
